services:
  api:
    container_name: apieasier_api
    hostname: apieasier_api
    restart: always
    image: apieasier_api
    build:
      context: ./src 
      dockerfile: ApiEasier.Api/Dockerfile
    env_file:
      - path: ./environment/default.env
        required: true
    networks:
      - backend
      - frontend 
  frontend:
    container_name: apieasier_frontend
    hostname: apieasier_frontend
    restart: always
    ports:
      - "5280:80"
    image: apieasier_frontend
    build:
      context: ./ApiEasier.Frontend/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend 


networks:
  backend:
    external: false
    driver: bridge
  frontend:
    external: false
    driver: bridge
