services:
  api:
    container_name: sota2b_api
    hostname: sota2b_api
    restart: always
    image: sota2b_api
    build:
      context: ./ 
      dockerfile: Sota2b.API/Dockerfile
    env_file:
      - path: ./environment/default.env
        required: true
    networks:
      - backend
      - frontend 
  frontend:
    container_name: sota2b_frontend
    hostname: sota2b_frontend
    restart: always
    ports:
      - "5280:80"
    image: sota2b_frontend
    build:
      context: ./Sota2b.Frontend/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend 


networks:
  backend:
    external: false
    driver: bridge
  frontend:
    external: false
    driver: bridge
